name: mikecunningham
favicon: null
layout_spectrum: 0.5266614705324173
typography_spectrum: 0.848649331368506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.49304324900731444
  lightness: 0.5929423540364951
  saturation: 0.9535537101328373
  rhythmicContrast: 0.4255083315074444
purpose: []
